//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UCMS.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link to confirm your account: &lt;a href=&apos;{0}&apos;&gt;Confirm your email&lt;/a&gt;.
        /// </summary>
        internal static string ConfirmationEmail_body {
            get {
                return ResourceManager.GetString("ConfirmationEmail_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        internal static string ConfirmationEmail_Subject {
            get {
                return ResourceManager.GetString("ConfirmationEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی،
        ///درخواست شما برای دریافت کد تأیید دریافت شد.
        ///
        ///کد یک‌بار مصرف شما:
        ///
        ///{0}
        ///
        ///این کد فقط به مدت 2 دقیقه معتبر است و تنها یک‌بار قابل استفاده می‌باشد.
        ///
        ///در صورتی که شما این درخواست را ارسال نکرده‌اید، لطفاً این ایمیل را نادیده بگیرید.
        ///
        ///با احترام،
        ///تیم پشتیبانی UCMS
        ///.
        /// </summary>
        internal static string OneTimeCode_body {
            get {
                return ResourceManager.GetString("OneTimeCode_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your one time code.
        /// </summary>
        internal static string OneTimeCode_subject {
            get {
                return ResourceManager.GetString("OneTimeCode_subject", resourceCulture);
            }
        }
    }
}
