//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UCMS.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account confirmed successfully.
        /// </summary>
        public static string AccountConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("AccountConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNotConfirmed.
        /// </summary>
        public static string AccountNotConfirmed {
            get {
                return ResourceManager.GetString("AccountNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All roles fetched successfully..
        /// </summary>
        public static string AllRolesFetchedSuccessfully {
            get {
                return ResourceManager.GetString("AllRolesFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users fetched successfully.
        /// </summary>
        public static string AllUsersFetchedSuccessfully {
            get {
                return ResourceManager.GetString("AllUsersFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already entered this class..
        /// </summary>
        public static string AlreadyEnteredThisClass_ {
            get {
                return ResourceManager.GetString("AlreadyEnteredThisClass.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyJoinedClass.
        /// </summary>
        public static string AlreadyJoinedClass {
            get {
                return ResourceManager.GetString("AlreadyJoinedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizedMessage.
        /// </summary>
        public static string AuthorizedMessage {
            get {
                return ResourceManager.GetString("AuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access the project..
        /// </summary>
        public static string CanNotAccessTheProject {
            get {
                return ResourceManager.GetString("CanNotAccessTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access the team..
        /// </summary>
        public static string CanNotAccessTheTeam {
            get {
                return ResourceManager.GetString("CanNotAccessTheTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class can&apos;t be accessed..
        /// </summary>
        public static string ClassCan_tBeAccessed {
            get {
                return ResourceManager.GetString("ClassCan\'tBeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class was created successfully..
        /// </summary>
        public static string ClassCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ClassCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Currently Not Active.
        /// </summary>
        public static string ClassCurrentlyNotActive {
            get {
                return ResourceManager.GetString("ClassCurrentlyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class deleted successfully..
        /// </summary>
        public static string ClassDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ClassDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes retrieved successfully..
        /// </summary>
        public static string ClassesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ClassesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class fetched successfully..
        /// </summary>
        public static string ClassFetchedSuccessfully {
            get {
                return ResourceManager.GetString("ClassFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class joined successfully..
        /// </summary>
        public static string ClassJoinedSuccessfully {
            get {
                return ResourceManager.GetString("ClassJoinedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not found..
        /// </summary>
        public static string ClassNotFound {
            get {
                return ResourceManager.GetString("ClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class updated successfully..
        /// </summary>
        public static string ClassUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ClassUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password confirmation is required..
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id = {0} deleted successfully..
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be at most 500 chars..
        /// </summary>
        public static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate student numbers..
        /// </summary>
        public static string DuplicateStudentNumbers {
            get {
                return ResourceManager.GetString("DuplicateStudentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already taken..
        /// </summary>
        public static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date can not be earlier than update time..
        /// </summary>
        public static string EndDateCanNotBeEarlierThanUpdateTime {
            get {
                return ResourceManager.GetString("EndDateCanNotBeEarlierThanUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be in the past..
        /// </summary>
        public static string EndDateCanNotBeInPast {
            get {
                return ResourceManager.GetString("EndDateCanNotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired code.
        /// </summary>
        public static string ExpiredCode {
            get {
                return ResourceManager.GetString("ExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileDoesNotExist.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access this resource.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس مورد نظر یافت نشد..
        /// </summary>
        public static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format is not valid..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidGroupSize.
        /// </summary>
        public static string InvalidGroupSize {
            get {
                return ResourceManager.GetString("InvalidGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidInputMessage.
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidIstructorForThisClass.
        /// </summary>
        public static string InvalidIstructorForThisClass {
            get {
                return ResourceManager.GetString("InvalidIstructorForThisClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidProjectForThisClass.
        /// </summary>
        public static string InvalidProjectForThisClass {
            get {
                return ResourceManager.GetString("InvalidProjectForThisClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidProjectTypeSelected.
        /// </summary>
        public static string InvalidProjectTypeSelected {
            get {
                return ResourceManager.GetString("InvalidProjectTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file size is not valid..
        /// </summary>
        public static string InvalidSize {
            get {
                return ResourceManager.GetString("InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid student number..
        /// </summary>
        public static string InvalidStudentNumber {
            get {
                return ResourceManager.GetString("InvalidStudentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template file format..
        /// </summary>
        public static string InvalidTemplateFileFormat {
            get {
                return ResourceManager.GetString("InvalidTemplateFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader student not in team..
        /// </summary>
        public static string LeaderStudentNotInTeam {
            get {
                return ResourceManager.GetString("LeaderStudentNotInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader student number is required..
        /// </summary>
        public static string LeaderStudentNumberIsRequired {
            get {
                return ResourceManager.GetString("LeaderStudentNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader student number max length..
        /// </summary>
        public static string LeaderStudentNumberMaxLength {
            get {
                return ResourceManager.GetString("LeaderStudentNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftClassNotSuccessfully.
        /// </summary>
        public static string LeftClassNotSuccessfully {
            get {
                return ResourceManager.GetString("LeftClassNotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Class Successfully.
        /// </summary>
        public static string LeftClassSuccessfully {
            get {
                return ResourceManager.GetString("LeftClassSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListOfStudent.
        /// </summary>
        public static string ListOfStudent {
            get {
                return ResourceManager.GetString("ListOfStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginSuccessfulMessage.
        /// </summary>
        public static string LoginSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoutSuccessfulyMessage.
        /// </summary>
        public static string LogoutSuccessfulyMessage {
            get {
                return ResourceManager.GetString("LogoutSuccessfulyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify new leader when deleting current leader..
        /// </summary>
        public static string MustSpecifyNewLeaderWhenDeletingCurrentLeader {
            get {
                return ResourceManager.GetString("MustSpecifyNewLeaderWhenDeletingCurrentLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneTimeCodeSent.
        /// </summary>
        public static string OneTimeCodeSent {
            get {
                return ResourceManager.GetString("OneTimeCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater then zero..
        /// </summary>
        public static string PageMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PageMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between 1 and 100..
        /// </summary>
        public static string PageSizeMustBeBetween1And100 {
            get {
                return ResourceManager.GetString("PageSizeMustBeBetween1And100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwrod changed successfully..
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is requires..
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do no.t match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not strong enough..
        /// </summary>
        public static string PasswordNotStrong {
            get {
                return ResourceManager.GetString("PasswordNotStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseAlreadyExists.
        /// </summary>
        public static string PhaseAlreadyExists {
            get {
                return ResourceManager.GetString("PhaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseCantBeAccessed.
        /// </summary>
        public static string PhaseCantBeAccessed {
            get {
                return ResourceManager.GetString("PhaseCantBeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseCantBeAccessed.
        /// </summary>
        public static string PhaseCantBeAccessedC {
            get {
                return ResourceManager.GetString("PhaseCantBeAccessedC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseCreatedSuccessfully.
        /// </summary>
        public static string PhaseCreatedSuccessfully {
            get {
                return ResourceManager.GetString("PhaseCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseFileDownloadedSuccessfully.
        /// </summary>
        public static string PhaseFileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("PhaseFileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseNotFound.
        /// </summary>
        public static string PhaseNotFound {
            get {
                return ResourceManager.GetString("PhaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseOrFileNotFound.
        /// </summary>
        public static string PhaseOrFileNotFound {
            get {
                return ResourceManager.GetString("PhaseOrFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseRetrievedSuccessfully.
        /// </summary>
        public static string PhaseRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("PhaseRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseScoreMustBePositive.
        /// </summary>
        public static string PhaseScoreMustBePositive {
            get {
                return ResourceManager.GetString("PhaseScoreMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhasesRetrievedSuccessfully.
        /// </summary>
        public static string PhasesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("PhasesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhaseUpdatedSuccessfully.
        /// </summary>
        public static string PhaseUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PhaseUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectCantBeAccessed.
        /// </summary>
        public static string ProjectCantBeAccessed {
            get {
                return ResourceManager.GetString("ProjectCantBeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectCreatedSuccessfully.
        /// </summary>
        public static string ProjectCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectDeletedSuccessfully.
        /// </summary>
        public static string ProjectDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectFileDownloadedSuccessfully.
        /// </summary>
        public static string ProjectFileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectFileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project id is required..
        /// </summary>
        public static string ProjectIdIsRequired {
            get {
                return ResourceManager.GetString("ProjectIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectNotFound.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectOrFileNotFound.
        /// </summary>
        public static string ProjectOrFileNotFound {
            get {
                return ResourceManager.GetString("ProjectOrFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectRetrievedSuccessfully.
        /// </summary>
        public static string ProjectRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectsRetrievedSuccessfully.
        /// </summary>
        public static string ProjectsRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectsRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectUpdatedSuccessfully.
        /// </summary>
        public static string ProjectUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        public static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس با موفقیت حذف شد..
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveStudentFromClassNotSuccessfully.
        /// </summary>
        public static string RemoveStudentFromClassNotSuccessfully {
            get {
                return ResourceManager.GetString("RemoveStudentFromClassNotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveStudentFromClassSuccessfully.
        /// </summary>
        public static string RemoveStudentFromClassSuccessfully {
            get {
                return ResourceManager.GetString("RemoveStudentFromClassSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schedules is required..
        /// </summary>
        public static string SchedulesRequired {
            get {
                return ResourceManager.GetString("SchedulesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some adding student already in team..
        /// </summary>
        public static string SomeAddingStudentAlreadyInTeam {
            get {
                return ResourceManager.GetString("SomeAddingStudentAlreadyInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some deleteing student not in team..
        /// </summary>
        public static string SomeDeleteingStudentNotInTeam {
            get {
                return ResourceManager.GetString("SomeDeleteingStudentNotInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some students already in another team..
        /// </summary>
        public static string SomeStudentsAlreadyInAnotherTeam {
            get {
                return ResourceManager.GetString("SomeStudentsAlreadyInAnotherTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some students not in class..
        /// </summary>
        public static string SomeStudentsNotInClass {
            get {
                return ResourceManager.GetString("SomeStudentsNotInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date can not be earlier than creation time..
        /// </summary>
        public static string StartDateCanNotBeEarlierThanCreationTime {
            get {
                return ResourceManager.GetString("StartDateCanNotBeEarlierThanCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be in the past..
        /// </summary>
        public static string StartDateCanNotBeInPast {
            get {
                return ResourceManager.GetString("StartDateCanNotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be later than end date..
        /// </summary>
        public static string StartDateCanNotBeLaterThanEndDatte {
            get {
                return ResourceManager.GetString("StartDateCanNotBeLaterThanEndDatte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Not In Class.
        /// </summary>
        public static string StudentNotInClass {
            get {
                return ResourceManager.GetString("StudentNotInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student numbers is required..
        /// </summary>
        public static string StudentNumbersIsRequired {
            get {
                return ResourceManager.GetString("StudentNumbersIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team created successfully..
        /// </summary>
        public static string TeamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TeamCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team deleted successfully..
        /// </summary>
        public static string TeamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TeamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team fetched successfully..
        /// </summary>
        public static string TeamFetchedSuccessfully {
            get {
                return ResourceManager.GetString("TeamFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team file validated successfuly..
        /// </summary>
        public static string TeamFileValidatedSuccessfuly {
            get {
                return ResourceManager.GetString("TeamFileValidatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team leader is not memeber of team..
        /// </summary>
        public static string TeamLeaderIsNotMemeberOfTeam {
            get {
                return ResourceManager.GetString("TeamLeaderIsNotMemeberOfTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name is required..
        /// </summary>
        public static string TeamNameIsRequired {
            get {
                return ResourceManager.GetString("TeamNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name max length..
        /// </summary>
        public static string TeamNameMaxLength {
            get {
                return ResourceManager.GetString("TeamNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found..
        /// </summary>
        public static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TeamsCanNotBeCreated {
            get {
                return ResourceManager.GetString("TeamsCanNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams created successfully..
        /// </summary>
        public static string TeamsCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TeamsCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams fetched successfully..
        /// </summary>
        public static string TeamsFetchedSuccessfully {
            get {
                return ResourceManager.GetString("TeamsFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team size is out of limit..
        /// </summary>
        public static string TeamSizeOutOfLimit {
            get {
                return ResourceManager.GetString("TeamSizeOutOfLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team template file generated successfully..
        /// </summary>
        public static string TeamTemplateFileGeneratedSuccessfully {
            get {
                return ResourceManager.GetString("TeamTemplateFileGeneratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team updated successfully..
        /// </summary>
        public static string TeamUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TeamUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be at most 100 chars..
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalScoreMustBePositive.
        /// </summary>
        public static string TotalScoreMustBePositive {
            get {
                return ResourceManager.GetString("TotalScoreMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedAccess.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedMessage.
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user with id = {0} updated successfully..
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس با موفقیت بارگذاری شد..
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id = {0} found..
        /// </summary>
        public static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken..
        /// </summary>
        public static string UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id = {0} not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFoundMessage.
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongPasswordMessage.
        /// </summary>
        public static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
    }
}
