//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UCMS.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account confirmed successfully.
        /// </summary>
        public static string AccountConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("AccountConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All roles fetched successfully..
        /// </summary>
        public static string AllRolesFetchedSuccessfully {
            get {
                return ResourceManager.GetString("AllRolesFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already entered this class..
        /// </summary>
        public static string AlreadyEnteredThisClass_ {
            get {
                return ResourceManager.GetString("AlreadyEnteredThisClass.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyJoinedClass.
        /// </summary>
        public static string AlreadyJoinedClass {
            get {
                return ResourceManager.GetString("AlreadyJoinedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorizedMessage.
        /// </summary>
        public static string AuthorizedMessage {
            get {
                return ResourceManager.GetString("AuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class can&apos;t be accessed..
        /// </summary>
        public static string ClassCan_tBeAccessed {
            get {
                return ResourceManager.GetString("ClassCan\'tBeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class was created successfully..
        /// </summary>
        public static string ClassCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ClassCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Currently Not Active.
        /// </summary>
        public static string ClassCurrentlyNotActive {
            get {
                return ResourceManager.GetString("ClassCurrentlyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class deleted successfully..
        /// </summary>
        public static string ClassDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ClassDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes retrieved successfully..
        /// </summary>
        public static string ClassesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ClassesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class fetched successfully..
        /// </summary>
        public static string ClassFetchedSuccessfully {
            get {
                return ResourceManager.GetString("ClassFetchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class joined successfully..
        /// </summary>
        public static string ClassJoinedSuccessfully {
            get {
                return ResourceManager.GetString("ClassJoinedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not found..
        /// </summary>
        public static string ClassNotFound {
            get {
                return ResourceManager.GetString("ClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class updated successfully..
        /// </summary>
        public static string ClassUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ClassUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already taken..
        /// </summary>
        public static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be in the past..
        /// </summary>
        public static string EndDateCanNotBeInPast {
            get {
                return ResourceManager.GetString("EndDateCanNotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired code.
        /// </summary>
        public static string ExpiredCode {
            get {
                return ResourceManager.GetString("ExpiredCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format is not valid..
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidInputMessage.
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file size is not valid..
        /// </summary>
        public static string InvalidSize {
            get {
                return ResourceManager.GetString("InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftClassNotSuccessfully.
        /// </summary>
        public static string LeftClassNotSuccessfully {
            get {
                return ResourceManager.GetString("LeftClassNotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Class Successfully.
        /// </summary>
        public static string LeftClassSuccessfully {
            get {
                return ResourceManager.GetString("LeftClassSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListOfStudent.
        /// </summary>
        public static string ListOfStudent {
            get {
                return ResourceManager.GetString("ListOfStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginSuccessfulMessage.
        /// </summary>
        public static string LoginSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogoutSuccessfulyMessage.
        /// </summary>
        public static string LogoutSuccessfulyMessage {
            get {
                return ResourceManager.GetString("LogoutSuccessfulyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneTimeCodeSent.
        /// </summary>
        public static string OneTimeCodeSent {
            get {
                return ResourceManager.GetString("OneTimeCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do no.t match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not strong enough..
        /// </summary>
        public static string PasswordNotStrong {
            get {
                return ResourceManager.GetString("PasswordNotStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        public static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveStudentFromClassNotSuccessfully.
        /// </summary>
        public static string RemoveStudentFromClassNotSuccessfully {
            get {
                return ResourceManager.GetString("RemoveStudentFromClassNotSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveStudentFromClassSuccessfully.
        /// </summary>
        public static string RemoveStudentFromClassSuccessfully {
            get {
                return ResourceManager.GetString("RemoveStudentFromClassSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date can not be earlier than creation time..
        /// </summary>
        public static string StartDateCanNotBeEarlierThanCreationTime {
            get {
                return ResourceManager.GetString("StartDateCanNotBeEarlierThanCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be in the past..
        /// </summary>
        public static string StartDateCanNotBeInPast {
            get {
                return ResourceManager.GetString("StartDateCanNotBeInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be later than end date..
        /// </summary>
        public static string StartDateCanNotBeLaterThanEndDatte {
            get {
                return ResourceManager.GetString("StartDateCanNotBeLaterThanEndDatte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentNotFound.
        /// </summary>
        public static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Not In Class.
        /// </summary>
        public static string StudentNotInClass {
            get {
                return ResourceManager.GetString("StudentNotInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedAccess.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnauthorizedMessage.
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken..
        /// </summary>
        public static string UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFoundMessage.
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongPasswordMessage.
        /// </summary>
        public static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
    }
}
