
services:
  server:
    build:
      context: .
      target: runtime
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=db;Port=5432;Database=UCMS;Username=postgres;Password=@Simpleuser01
      - ORIGIN_URL=http://2.189.242.228:81
    depends_on:
      - db
    command: >
      sh -c "
        until pg_isready -h db -U postgres; do echo 'Waiting for DB...'; sleep 2; done &&
        dotnet UCMS.dll"

  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Simpleuser01"
      POSTGRES_DB: UCMS
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
