# This workflow will build a .NET project  

name: .NET  

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "dev" ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v4  
    - name: Setup .NET  
      uses: actions/setup-dotnet@v4  
      with:  
        dotnet-version: 8.0.x  
        
    - name: Define Project Path  
      id: project-path  
      run: echo "PROJECT_PATH=UCMS_Implementation/UCMS/UCMS.csproj" >> $GITHUB_ENV  
      
    - name: Restore dependencies  
      run: dotnet restore ${{ env.PROJECT_PATH }}  
      
    - name: Build  
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore  
      
    - name: Test  
      run: dotnet test dotnet test UCMS_Implementation\UCMS_Test\UCMS_Test.csproj --configuration Release --no-build --verbosity normal  
